### ISSUE TITLE
Typescript compatibility error

### ISSUE THREAD

**Issue by javieerrubio11** [cloydlau/json-editor-vue#27] opened 2022-11-29 11:15 UTC
Hello,

I want use the version Vue 2.6 or Earlier so I execute the following command:
`npm add json-editor-vue vanilla-jsoneditor @vue/composition-api`

When I use the next line:
`import VueJsonEditor from 'vue-json-editor'`

It produces the next error:
```
./node_modules/json-editor-vue/dist/json-editor-vue.mjs 1377:8-10
Can't import the named export 'defineComponent' from non EcmaScript module (only default export is available)
```

So my question is If the plugin is compatible with Typescript.

Note: I tried to use the import from:
`vue-json-editor/dist`
but It didn't works for me.

Tahnks.

**Comment by cloydlau** [comment] 2022-11-29 14:21
I think you are using the wrong lib. The `vue-json-editor` you mentioned has not been updated for 2 years.
Give https://github.com/cloydlau/json-editor-vue/tree/main/demo/vue2.6 a try, it works quite fine.
Lack of sufficient information. Please provide a [minimal reproduction](https://codesandbox.io) thanks.
> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by cloydlau** [comment] 2022-11-30 06:06
Temporarily close this due to the lack of sufficient information.
Please provide a [minimal reproduction](https://codesandbox.io) to reopen the issue.
Thanks.
> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by cloydlau** 2022-11-30 06:06 UTC

**Comment by javieerrubio11** [comment] 2022-11-30 17:39
Hi @cloydlau  

I tried to use the example that you provided me. 
However, when I install the library with this code (node version 15):
`yarn add json-editor-vue vanilla-jsoneditor @vue/composition-api`

I don't have acces to /src folder as in the example [provided](https://github.com/cloydlau/json-editor-vue/tree/main/demo/vue2.6):
```
...
import JsonEditorVue from '../../src'
...
```

I only have acces the to next structure of files:
```
/dist
/doces
/node_modules
LICENSE
package.json
README.md
```


However, I've seen that the component uses that library: https://github.com/josdejong/svelte-jsoneditor

So I've done my custom implementation in Vue with the minimum tools that I need.
https://codesandbox.io/s/svelte-jsoneditor-vue-toln3w?file=/src/components/VueJSONEditor.vue


Thanks for everything :D
However, I have not known how to use it with typescript. Sorry for the inconvenience.

**Comment by cloydlau** [comment] 2022-12-01 01:38
Hello.
`'../../src'` is for development and should be, of course, replaced with `'json-editor-vue'` in production. I should've pointed that out though. It's my bad.
`json-editor-vue` is built with TypeScript, there should be no barriers using it in TypeScript. The example I gave is also written in TypeScript.
Reach out to me if you found any further issue related to `json-editor-vue`.
